Sprint 1/step 2
Chill-Peppa/react-burger pull request #2
Opened 2023-09-28 17:53 UTC by Chill-Peppa

2023-09-29 10:34 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали отличную и очень аккуратную работу на втором этапе вашего спринта, удачно организовали новые компоненты и работу с API, **так держать!** 👍 

Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- "Магические" значения (см. https://ru.wikipedia.org/wiki/Магическое_число_(программирование)) следует выносить в константы, чтобы наглядно показать, что они означают;
- У `ModalOverlay` не должно быть `children`, т.к. по задумке - это просто компонент подложки а не контейнер;
- Проверка типа ингредиента в списке карточек не требуется, т.к. на вход поступают уже отфильтрованные данные;

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу/

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-09-29 10:34 UTC, randomroot commented on src/components/app-header/app-header.jsx
> +          <Link to="/">
🟢 **Отлично:**

Хорошая деталь по взаимодействию с интерфейсом 👍

2023-09-29 10:34 UTC, randomroot commented on src/components/modal/modal.jsx
> +      if (e.keyCode === 27) {
🔴 **Нужно исправить:**

"Магические" значения (см. https://ru.wikipedia.org/wiki/Магическое_число_(программирование)) следует выносить в константы, чтобы наглядно показать, что они означают

2023-09-29 10:34 UTC, randomroot commented on src/components/modal/modal.jsx
> +    <ModalOverlay onCloseOverlay={onClose}>
🔴 **Нужно исправить:**

У `ModalOverlay` не должно быть `children`, т.к. по задумке - это просто компонент подложки а не контейнер

2023-09-29 10:34 UTC, randomroot commented on src/components/modal/modal.jsx
> +  title: PropTypes.string.isRequired,
🟡 **Можно улучшить:**

Заголовок имеет смысл сделать необязательным, чтобы не передавать пустую строку, когда он требуется

2023-09-29 10:34 UTC, randomroot commented on src/components/modal/modal.jsx
> +  const modalRoot = document.getElementById('react-modals');
🟡 **Можно улучшить:**

Имеет смысл вынести переменную за пределы компоненты. чтобы не пересоздавать её на каждом рендере

2023-09-29 10:34 UTC, randomroot commented on src/components/ingredient-card/ingredient-card.jsx
> +    console.log('на меня кликнули');
🟡 **Можно улучшить:**

Логи, используемые для отладки, рекомендуется удалять при сдаче работы, чтобы поддерживать чистоту вашего кода и консоли :)

2023-09-29 10:34 UTC, randomroot commented on src/components/ingredient-card-list/ingredient-card-list.jsx
> +  ingredientsArray: PropTypes.arrayOf(ingredientsDataType.isRequired)
🟢 **Отлично:**

Хорошо, что учитываете обязательность элементов массива 👍

2023-09-29 10:34 UTC, randomroot commented on src/components/ingredient-card-list/ingredient-card-list.jsx
> +            ingredient.type === typeIngredient && (
🔴 **Нужно исправить:**

Проверка здесь является излишней, т.к. вы уже в родительском компоненте провели фильтрацию данных

2023-09-29 10:34 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    (ingredient) => ingredient.type === `${tabs.BUN}`,
🟡 **Можно улучшить:**

Оборачивать `tabs.BUN` в строку отдельно не требуется, т.к. при обращении к нему вернется строка и так :)

2023-09-29 10:34 UTC, randomroot commented on src/utils/api.js
> +export default class Api {
🟢 **Отлично:**

Прекрасно построенный класс для работы с API 👍

2023-09-29 10:34 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +  console.log(ingredientsData);
🟡 **Можно улучшить:**

Логгирование ингредиентов после отладки рекомендуется убрать

2023-09-29 10:34 UTC, randomroot commented on src/components/app/app.jsx
> +    setSelectedIngredient({});
🟡 **Можно улучшить:**

В качестве пустого значения лучше использовать `null` или `undefined`, вместо пустого объекта

2023-09-30 06:50 UTC, Chill-Peppa commented
Большое спасибо за ревью!

2023-09-30 11:10 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-09-30 15:32 UTC, merged